## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'piezoconcept'  #for instance daqmx
package-url = 'https://github.com/CEMES-CNRS/pymodaq_plugins_piezoconcept' #to modify
description = 'Set of PyMoDAQ plugins for Actuators from Piezoconcept (Tested on the Bio200 XY stage. Include a version of the controller firmware emulating functions from PhysikInstrumente)'

author = 'Sébastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pyserial', 'pyvisa']
##